### ISSUE TITLE
undefined method `strip' for nil:NilClass

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-un#226]
Full logs https://github.com/metanorma/metanorma-cli/actions/runs/7865252554/job/21466114012#step:7:37
```

undefined method `strip' for nil:NilClass
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/isodoc-2.8.1/lib/isodoc/presentation_function/inline.rb:100:in `date1'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/isodoc-2.8.1/lib/isodoc/presentation_function/inline.rb:95:in `block in date'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.5-x86_64-darwin/lib/nokogiri/xml/node_set.rb:235:in `block in each'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.5-x86_64-darwin/lib/nokogiri/xml/node_set.rb:234:in `upto'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.5-x86_64-darwin/lib/nokogiri/xml/node_set.rb:234:in `each'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/isodoc-2.8.1/lib/isodoc/presentation_function/inline.rb:94:in `date'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/isodoc-2.8.1/lib/isodoc/presentation_xml_convert.rb:94:in `inline'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/isodoc-2.8.1/lib/isodoc/presentation_xml_convert.rb:45:in `conversions'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/isodoc-2.8.1/lib/isodoc/presentation_xml_convert.rb:25:in `convert1'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/isodoc-2.8.1/lib/isodoc/convert.rb:155:in `convert'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/metanorma-un-0.12.1/lib/metanorma/un/processor.rb:47:in `output'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/metanorma-1.7.0/lib/metanorma/compile.rb:170:in `process_output_unthreaded'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/metanorma-1.7.0/lib/metanorma/compile.rb:156:in `process_exts1'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/metanorma-1.7.0/lib/metanorma/compile.rb:130:in `process_ext'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/metanorma-1.7.0/lib/metanorma/compile.rb:112:in `block in process_exts_run'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/metanorma-1.7.0/lib/metanorma/compile.rb:111:in `each'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/metanorma-1.7.0/lib/metanorma/compile.rb:111:in `process_exts_run'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/metanorma-1.7.0/lib/metanorma/compile.rb:106:in `process_exts'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/metanorma-1.7.0/lib/metanorma/compile.rb:36:in `compile'
/Users/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/compiler.rb:45:in `compile_file'
/Users/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/compiler.rb:30:in `compile'
/Users/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/compiler.rb:35:in `compile'
/Users/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/site_generator.rb:96:in `compile'
/Users/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/site_generator.rb:32:in `block in generate'
/Users/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/site_generator.rb:32:in `map'
/Users/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/site_generator.rb:32:in `generate'
/Users/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/site_generator.rb:26:in `generate'
/Users/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/commands/site.rb:33:in `generate'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:116:in `invoke'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:243:in `block in subcommand'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
/Users/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli.rb:34:in `start'
/Users/runner/work/metanorma-cli/metanorma-cli/exe/metanorma:25:in `block in <top (required)>'
/Users/runner/work/metanorma-cli/metanorma-cli/exe/metanorma:43:in `<top (required)>'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/bin/metanorma:25:in `load'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/bin/metanorma:25:in `<top (required)>'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/3.2.0/bundler/cli.rb:492:in `exec'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/libexec/bundle:37:in `block in <top (required)>'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/libexec/bundle:29:in `<top (required)>'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/bin/bundle:25:in `load'
/Users/runner/hostedtoolcache/Ruby/3.2.3/x64/bin/bundle:25:in `<main>'
```

**Comment by opoudjis** [comment]
Addressed in https://github.com/metanorma/isodoc/commit/e03403bb796f1af9119099640e1a48784f8ecae2
