### ISSUE TITLE
 undefined method `image_resize' for #<Html2Doc:0x00007f0ed61dbf50

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-un#229]
```
undefined method `image_resize' for #<Html2Doc:0x00007f24c789b938 @filename=nil, @dir=nil, @dir1="_files", @header_file=nil, @asciimathdelims=nil, @imagedir=nil, @debug=nil, @liststyles=nil, @stylesheet=nil, @c=#<HTMLEntities:0x00007f24c789b230 @flavor="xhtml1">>

            Html2Doc.new({}).image_resize(i, image_localfile(i), @maxheight,
                            ^^^^^^^^^^^^^
/__tebako_memfs__/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/word_function/postprocess.rb:39:in `block in word_admonition_images'
/__tebako_memfs__/lib/ruby/gems/3.1.0/gems/nokogiri-1.15.5/lib/nokogiri/xml/node_set.rb:235:in `block in each'
/__tebako_memfs__/lib/ruby/gems/3.1.0/gems/nokogiri-1.15.5/lib/nokogiri/xml/node_set.rb:234:in `upto'
/__tebako_memfs__/lib/ruby/gems/3.1.0/gems/nokogiri-1.15.5/lib/nokogiri/xml/node_set.rb:234:in `each'
/__tebako_memfs__/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/word_function/postprocess.rb:37:in `word_admonition_images'
/__tebako_memfs__/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/word_function/postprocess.rb:54:in `word_cleanup'
/__tebako_memfs__/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/word_function/postprocess.rb:18:in `toWord'
/__tebako_memfs__/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/word_function/postprocess.rb:13:in `postprocess'
/__tebako_memfs__/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/convert.rb:158:in `convert'
/__tebako_memfs__/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/word_convert.rb:20:in `convert'
/__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-un-0.12.3/lib/metanorma/un/processor.rb:43:in `output'
/__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/compile.rb:161:in `process_output_threaded'
/__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/compile.rb:153:in `block in process_exts1'
/__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/worker_pool.rb:11:in `block (4 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/worker_pool.rb:9:in `loop'
/__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/worker_pool.rb:9:in `block (3 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/worker_pool.rb:8:in `catch'
/__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/worker_pool.rb:8:in `block (2 levels) in initialize'
```

This was spotted on `packed-mn` and `docker`:
- https://github.com/metanorma/packed-mn/actions/runs/7972159060/job/21763762268#step:11:19
- https://github.com/metanorma/metanorma-docker/actions/runs/7971553994/job/21761942119

**Comment by CAMOBAP** [comment]
Across all deliverable this issue was failed only on metanorma-docker becasue `--strict` flag was applied

@opoudjis @ronaldtse will you agree to use `--strict` in `metanorma-cli` workflow?

**Comment by opoudjis** [comment]
Yes, I agree to that. Better I catch these things in cli, than you do in docker.
